In [4]:
import numpy as np

In [5]:
lst = [1,2,3,4,5,6,7,8]
arr = np.array(lst)
for i in arr:
    print(i)

1
2
3
4
5
6
7
8


In [6]:
type(arr)

numpy.ndarray

In [7]:
print(type(lst))

<class 'list'>


In [8]:
arr[5]

6

In [9]:
arr[3:8]

array([4, 5, 6, 7, 8])

In [10]:
arr  * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [11]:
arr.argsort()

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [12]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
lst2d = [[1,2,3],[4,5,6],[7,8,9]]
lst2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
lst2 = np.array(lst2d)

In [15]:
lst2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
lst2[2:8:2]

array([[7, 8, 9]])

In [17]:
lst = [[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18,],[19,20,21,22,23,24,25,26,29]]

In [18]:
lst2 = np.array(lst)

In [19]:
lst2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 29]])

In [20]:
lst2[2,5]

24

In [21]:
lst2[1:2,0:9]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [22]:
lst2[1:3,4:7]

array([[14, 15, 16],
       [23, 24, 25]])

In [23]:
arr2d = np.arange(36).reshape(4,9)

In [24]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [25]:
arr2d[1:3,4:6]

array([[13, 14],
       [22, 23]])

In [26]:
arr2d[0:4,6:9]

array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26],
       [33, 34, 35]])

In [27]:
arr2d[:,5:7]

array([[ 5,  6],
       [14, 15],
       [23, 24],
       [32, 33]])

In [28]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [29]:
arr2d[:,[8,3,5,0,0]]

array([[ 8,  3,  5,  0,  0],
       [17, 12, 14,  9,  9],
       [26, 21, 23, 18, 18],
       [35, 30, 32, 27, 27]])

In [30]:
arr2d[[0,3,2],[1,8,5]]

array([ 1, 35, 23])

In [31]:
arr2d[:,::-3]

array([[ 8,  5,  2],
       [17, 14, 11],
       [26, 23, 20],
       [35, 32, 29]])

In [32]:
arr3d = np.arange(64).reshape(4,4,4)

In [33]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [34]:
arr3d[2][1][0]

36

In [35]:
arr3d[2,1,0]

36

In [36]:
arr3d[2,1,0:3]

array([36, 37, 38])

In [37]:
arr3d[0:3,1:3,0:2]

array([[[ 4,  5],
        [ 8,  9]],

       [[20, 21],
        [24, 25]],

       [[36, 37],
        [40, 41]]])

In [38]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [39]:
arr3d[:,2,1:3]

array([[ 9, 10],
       [25, 26],
       [41, 42],
       [57, 58]])

In [40]:
a=np.random.randint(1,15)

In [41]:
a

2

In [42]:
arr = np.arange(9).reshape(3,3)

In [43]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
arr2 = arr.T

In [45]:
arr*arr2

array([[ 0,  3, 12],
       [ 3, 16, 35],
       [12, 35, 64]])

In [46]:
arr+arr2

array([[ 0,  4,  8],
       [ 4,  8, 12],
       [ 8, 12, 16]])

In [47]:
import numpy as np

In [50]:
lst = [1,2,3,4,5,6,7,8,9]

In [51]:
arr1d = np.array(lst)

In [52]:
arr1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr1d[arr1d>5]

array([6, 7, 8, 9])

In [54]:
arr1d[arr1d==5]

array([5])

In [55]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [61]:
arr2d[arr2d>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [62]:
arr2d[(arr2d>10) & (arr2d<30)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

In [63]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [69]:
array_c = arr3d.ravel()

In [70]:
array_c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [72]:
array_c[10:40]=100

In [73]:
array_c

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63])

In [74]:
arr3d

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9, 100, 100],
        [100, 100, 100, 100]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]],

       [[ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59],
        [ 60,  61,  62,  63]]])

In [75]:
arr3d

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9, 100, 100],
        [100, 100, 100, 100]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]],

       [[ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59],
        [ 60,  61,  62,  63]]])

In [76]:
arr3d = np.arange(64).reshape(4,4,4)

In [77]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [78]:
c = arr3d.flatten()

In [80]:
c[6:40]=100

In [81]:
c

array([  0,   1,   2,   3,   4,   5, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63])

In [85]:
new_array =np.concatenate([arr2d,arr2d],axis=0)

In [86]:
new_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [90]:
a = np.arange(12).reshape(4,3)

In [91]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [95]:
b = np.arange(3).reshape(1,3)

In [96]:
b

array([[0, 1, 2]])

In [98]:
a+b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [99]:
x = np.array([[1],[2],[3]])
y = np.array([4,5,6])
c = np.broadcast(x,y)


In [104]:
c

In [102]:
out = np.empty(c.shape)

In [103]:
out

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 9.20938364e-321],
       [2.22523004e-307, 2.44029516e-312, 6.01346953e-154]])

In [105]:
import pandas as pd

In [106]:
s1 = pd.Series(["Ahmad","ali","XYZ"])

In [108]:
s1

0    Ahmad
1      ali
2      XYZ
dtype: object

In [109]:
s1[0]

'Ahmad'

In [110]:
s1[1]

'ali'

In [112]:
s1[2]

'XYZ'

In [114]:
print(type(s1))

<class 'pandas.core.series.Series'>


In [115]:
s1[0:2]

0    Ahmad
1      ali
dtype: object

In [119]:
s1[ s1=='Ahmad']

0    Ahmad
dtype: object

In [144]:
s2=pd.Series([1,5,6,7,8,9],index=['apple','banana','pine','guava','pine','coldrink'])

In [145]:
s2

apple       1
banana      5
pine        6
guava       7
pine        8
coldrink    9
dtype: int64

In [146]:
s2*2

apple        2
banana      10
pine        12
guava       14
pine        16
coldrink    18
dtype: int64

In [147]:
s3=pd.Series([20,51,72,36,43,51],index=[0,1,2,3,4,5])

In [148]:
s3

0    20
1    51
2    72
3    36
4    43
5    51
dtype: int64

In [149]:
s3*2

0     40
1    102
2    144
3     72
4     86
5    102
dtype: int64

In [150]:
s3.loc[2:6]

2    72
3    36
4    43
5    51
dtype: int64

In [151]:
s3.iloc[2:6]

2    72
3    36
4    43
5    51
dtype: int64

In [152]:
s3+s2

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
apple      NaN
banana     NaN
coldrink   NaN
guava      NaN
pine       NaN
pine       NaN
dtype: float64